import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    {
      type: 'doc',
      id: 'intro', // Main introduction page
    },
    {
      type: 'category',
      label: 'Chapter 1: Introduction to Physical AI',
      items: [
        {
          type: 'autogenerated',
          dirName: 'chapter-1',
        },
      ],
    },
    {
      type: 'category',
      label: 'Chapter 2: Humanoid Robotics Fundamentals',
      items: [
        {
          type: 'autogenerated',
          dirName: 'chapter-2',
        },
      ],
    },
    {
      type: 'category',
      label: 'Chapter 3: Sensor Integration & Perception',
      items: [
        {
          type: 'autogenerated',
          dirName: 'chapter-3',
        },
      ],
    },
    {
      type: 'category',
      label: 'Chapter 4: Control Systems & Actuation',
      items: [
        {
          type: 'autogenerated',
          dirName: 'chapter-4',
        },
      ],
    },
    {
      type: 'category',
      label: 'Chapter 5: AI Decision Making & Learning',
      items: [
        {
          type: 'autogenerated',
          dirName: 'chapter-5',
        },
      ],
    },
  ],

  // Urdu sidebar
  urSidebar: [
    {
      type: 'doc',
      id: 'ur/intro', // Urdu introduction page
    },
    {
      type: 'category',
      label: 'چیپٹر 1: فزیکل اے آئی کا تعارف',
      items: [
        {
          type: 'autogenerated',
          dirName: 'ur/chapter-1',
        },
      ],
    },
    {
      type: 'category',
      label: 'چیپٹر 2: ہیومنوائڈ روبوٹکس کے بنیادیات',
      items: [
        {
          type: 'autogenerated',
          dirName: 'ur/chapter-2',
        },
      ],
    },
    {
      type: 'category',
      label: 'چیپٹر 3: سینسر انٹیگریشن اور ادراک',
      items: [
        {
          type: 'autogenerated',
          dirName: 'ur/chapter-3',
        },
      ],
    },
    {
      type: 'category',
      label: 'چیپٹر 4: کنٹرول سسٹم اور ایکٹو ایشن',
      items: [
        {
          type: 'autogenerated',
          dirName: 'ur/chapter-4',
        },
      ],
    },
    {
      type: 'category',
      label: 'چیپٹر 5: اے آئی فیصلہ سازی اور سیکھنا',
      items: [
        {
          type: 'autogenerated',
          dirName: 'ur/chapter-5',
        },
      ],
    },
  ],
};

export default sidebars;
