openapi: 3.0.0
info:
  title: Authentication API for Physical AI Textbook
  version: 1.0.0
  description: API for user authentication and profile management

paths:
  /api/auth/register:
    post:
      summary: Register a new user
      description: Creates a new user account and collects background information
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
                - name
                - programmingLevel
                - roboticsFamiliarity
              properties:
                email:
                  type: string
                  format: email
                  description: User's email address
                password:
                  type: string
                  format: password
                  description: User's password
                name:
                  type: string
                  description: User's display name
                programmingLevel:
                  type: string
                  enum: [beginner, intermediate, advanced]
                  description: User's programming experience level
                roboticsFamiliarity:
                  type: string
                  enum: [none, basic, intermediate, advanced]
                  description: User's familiarity with robotics concepts
      responses:
        '201':
          description: User registered successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  user:
                    $ref: '#/components/schemas/User'
                  message:
                    type: string
        '400':
          description: Invalid input data
        '409':
          description: User with this email already exists

  /api/auth/login:
    post:
      summary: Login user
      description: Authenticates user and returns session token
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
              properties:
                email:
                  type: string
                  format: email
                password:
                  type: string
                  format: password
      responses:
        '200':
          description: Login successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  token:
                    type: string
                  user:
                    $ref: '#/components/schemas/User'
        '401':
          description: Invalid credentials

  /api/auth/profile:
    get:
      summary: Get user profile
      description: Retrieve the authenticated user's profile information
      security:
        - bearerAuth: []
      responses:
        '200':
          description: User profile retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
    put:
      summary: Update user profile
      description: Update the authenticated user's profile information
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                programmingLevel:
                  type: string
                  enum: [beginner, intermediate, advanced]
                roboticsFamiliarity:
                  type: string
                  enum: [none, basic, intermediate, advanced]
                preferences:
                  type: object
                  properties:
                    preferredLanguage:
                      type: string
                      enum: [en, ur]
                    contentDepth:
                      type: string
                      enum: [basic, intermediate, advanced]
      responses:
        '200':
          description: Profile updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'

components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: string
        email:
          type: string
          format: email
        name:
          type: string
        programmingLevel:
          type: string
          enum: [beginner, intermediate, advanced]
        roboticsFamiliarity:
          type: string
          enum: [none, basic, intermediate, advanced]
        preferences:
          type: object
          properties:
            preferredLanguage:
              type: string
              enum: [en, ur]
            contentDepth:
              type: string
              enum: [basic, intermediate, advanced]
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT